/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddJobRequest {
  'title' : string,
  'contactInfo' : string,
  'isRemote' : boolean,
  'description' : string,
  'category' : Category,
  'salaryMax' : bigint,
  'salaryMin' : bigint,
  'requirements' : string,
  'location' : string,
}
export type BoliviaCity = { 'LaPaz' : null } |
  { 'Sucre' : null } |
  { 'Beni' : null } |
  { 'Potosi' : null } |
  { 'Cochabamba' : null } |
  { 'Pando' : null } |
  { 'SantaCruz' : null } |
  { 'Tarija' : null } |
  { 'Oruro' : null } |
  { 'ElAlto' : null };
export type Category = { 'Electricista' : null } |
  { 'Mecanico' : null } |
  { 'Plomero' : null } |
  { 'Albanil' : null } |
  { 'Carpintero' : null } |
  { 'Soldador' : null } |
  { 'Pintor' : null } |
  { 'Otros' : null } |
  { 'Jardinero' : null };
export type JobId = bigint;
export type JobStatus = { 'Posted' : null } |
  { 'Cancelled' : null } |
  { 'PendingApproval' : null } |
  { 'InProgress' : null } |
  { 'Completed' : null };
export interface JobView {
  'id' : JobId,
  'title' : string,
  'postedBy' : [] | [UserId],
  'contactInfo' : string,
  'postedDate' : Timestamp,
  'jobStatus' : JobStatus,
  'assignedWorker' : [] | [UserId],
  'isRemote' : boolean,
  'description' : string,
  'category' : Category,
  'salaryMax' : bigint,
  'salaryMin' : bigint,
  'requirements' : string,
  'location' : string,
}
export interface PageResult {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
  'items' : Array<JobView>,
}
export type ProfileStatus = { 'Active' : null } |
  { 'Suspended' : null };
export interface RegisterRequest {
  'city' : BoliviaCity,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'phone' : string,
}
export type Timestamp = bigint;
export interface UpdateProfileRequest {
  'city' : BoliviaCity,
  'name' : string,
  'phone' : string,
}
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'balance' : number,
  'city' : BoliviaCity,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'profileStatus' : ProfileStatus,
  'phone' : string,
  'registeredAt' : Timestamp,
}
export type UserRole = { 'Trabajador' : null } |
  { 'Cliente' : null };
export interface _SERVICE {
  'addJob' : ActorMethod<[AddJobRequest], JobView>,
  'applyForJob' : ActorMethod<[JobId], { 'ok' : null } | { 'err' : string }>,
  'approveJob' : ActorMethod<[JobId], { 'ok' : null } | { 'err' : string }>,
  'filterJobsByCategory' : ActorMethod<[Category, bigint, bigint], PageResult>,
  'filterJobsByLocation' : ActorMethod<[string, bigint, bigint], PageResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getJob' : ActorMethod<[JobId], [] | [JobView]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerBalance' : ActorMethod<[], number>,
  'initSampleData' : ActorMethod<[], undefined>,
  'listJobs' : ActorMethod<[bigint, bigint], PageResult>,
  'markJobComplete' : ActorMethod<
    [JobId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<[RegisterRequest], UserProfile>,
  'searchJobs' : ActorMethod<[string, bigint, bigint], PageResult>,
  'topUpBalance' : ActorMethod<[number], { 'ok' : null } | { 'err' : string }>,
  'updateCallerUserProfile' : ActorMethod<[UpdateProfileRequest], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];