/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'Electricista' : IDL.Null,
  'Mecanico' : IDL.Null,
  'Plomero' : IDL.Null,
  'Albanil' : IDL.Null,
  'Carpintero' : IDL.Null,
  'Soldador' : IDL.Null,
  'Pintor' : IDL.Null,
  'Otros' : IDL.Null,
  'Jardinero' : IDL.Null,
});
export const AddJobRequest = IDL.Record({
  'title' : IDL.Text,
  'contactInfo' : IDL.Text,
  'isRemote' : IDL.Bool,
  'description' : IDL.Text,
  'category' : Category,
  'salaryMax' : IDL.Nat,
  'salaryMin' : IDL.Nat,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
});
export const JobId = IDL.Nat;
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const JobStatus = IDL.Variant({
  'Posted' : IDL.Null,
  'Cancelled' : IDL.Null,
  'PendingApproval' : IDL.Null,
  'InProgress' : IDL.Null,
  'Completed' : IDL.Null,
});
export const JobView = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'postedBy' : IDL.Opt(UserId),
  'contactInfo' : IDL.Text,
  'postedDate' : Timestamp,
  'jobStatus' : JobStatus,
  'assignedWorker' : IDL.Opt(UserId),
  'isRemote' : IDL.Bool,
  'description' : IDL.Text,
  'category' : Category,
  'salaryMax' : IDL.Nat,
  'salaryMin' : IDL.Nat,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
});
export const PageResult = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
  'items' : IDL.Vec(JobView),
});
export const BoliviaCity = IDL.Variant({
  'LaPaz' : IDL.Null,
  'Sucre' : IDL.Null,
  'Beni' : IDL.Null,
  'Potosi' : IDL.Null,
  'Cochabamba' : IDL.Null,
  'Pando' : IDL.Null,
  'SantaCruz' : IDL.Null,
  'Tarija' : IDL.Null,
  'Oruro' : IDL.Null,
  'ElAlto' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'Trabajador' : IDL.Null,
  'Cliente' : IDL.Null,
});
export const ProfileStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Suspended' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'balance' : IDL.Float64,
  'city' : BoliviaCity,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'profileStatus' : ProfileStatus,
  'phone' : IDL.Text,
  'registeredAt' : Timestamp,
});
export const RegisterRequest = IDL.Record({
  'city' : BoliviaCity,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const UpdateProfileRequest = IDL.Record({
  'city' : BoliviaCity,
  'name' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addJob' : IDL.Func([AddJobRequest], [JobView], []),
  'applyForJob' : IDL.Func(
      [JobId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'approveJob' : IDL.Func(
      [JobId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'filterJobsByCategory' : IDL.Func(
      [Category, IDL.Nat, IDL.Nat],
      [PageResult],
      ['query'],
    ),
  'filterJobsByLocation' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [PageResult],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getJob' : IDL.Func([JobId], [IDL.Opt(JobView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'initSampleData' : IDL.Func([], [], []),
  'listJobs' : IDL.Func([IDL.Nat, IDL.Nat], [PageResult], ['query']),
  'markJobComplete' : IDL.Func(
      [JobId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'registerUser' : IDL.Func([RegisterRequest], [UserProfile], []),
  'searchJobs' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [PageResult],
      ['query'],
    ),
  'topUpBalance' : IDL.Func(
      [IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateCallerUserProfile' : IDL.Func(
      [UpdateProfileRequest],
      [UserProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'Electricista' : IDL.Null,
    'Mecanico' : IDL.Null,
    'Plomero' : IDL.Null,
    'Albanil' : IDL.Null,
    'Carpintero' : IDL.Null,
    'Soldador' : IDL.Null,
    'Pintor' : IDL.Null,
    'Otros' : IDL.Null,
    'Jardinero' : IDL.Null,
  });
  const AddJobRequest = IDL.Record({
    'title' : IDL.Text,
    'contactInfo' : IDL.Text,
    'isRemote' : IDL.Bool,
    'description' : IDL.Text,
    'category' : Category,
    'salaryMax' : IDL.Nat,
    'salaryMin' : IDL.Nat,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
  });
  const JobId = IDL.Nat;
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const JobStatus = IDL.Variant({
    'Posted' : IDL.Null,
    'Cancelled' : IDL.Null,
    'PendingApproval' : IDL.Null,
    'InProgress' : IDL.Null,
    'Completed' : IDL.Null,
  });
  const JobView = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'postedBy' : IDL.Opt(UserId),
    'contactInfo' : IDL.Text,
    'postedDate' : Timestamp,
    'jobStatus' : JobStatus,
    'assignedWorker' : IDL.Opt(UserId),
    'isRemote' : IDL.Bool,
    'description' : IDL.Text,
    'category' : Category,
    'salaryMax' : IDL.Nat,
    'salaryMin' : IDL.Nat,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
  });
  const PageResult = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
    'items' : IDL.Vec(JobView),
  });
  const BoliviaCity = IDL.Variant({
    'LaPaz' : IDL.Null,
    'Sucre' : IDL.Null,
    'Beni' : IDL.Null,
    'Potosi' : IDL.Null,
    'Cochabamba' : IDL.Null,
    'Pando' : IDL.Null,
    'SantaCruz' : IDL.Null,
    'Tarija' : IDL.Null,
    'Oruro' : IDL.Null,
    'ElAlto' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'Trabajador' : IDL.Null,
    'Cliente' : IDL.Null,
  });
  const ProfileStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Suspended' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'balance' : IDL.Float64,
    'city' : BoliviaCity,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'profileStatus' : ProfileStatus,
    'phone' : IDL.Text,
    'registeredAt' : Timestamp,
  });
  const RegisterRequest = IDL.Record({
    'city' : BoliviaCity,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UpdateProfileRequest = IDL.Record({
    'city' : BoliviaCity,
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addJob' : IDL.Func([AddJobRequest], [JobView], []),
    'applyForJob' : IDL.Func(
        [JobId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'approveJob' : IDL.Func(
        [JobId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'filterJobsByCategory' : IDL.Func(
        [Category, IDL.Nat, IDL.Nat],
        [PageResult],
        ['query'],
      ),
    'filterJobsByLocation' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [PageResult],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getJob' : IDL.Func([JobId], [IDL.Opt(JobView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'initSampleData' : IDL.Func([], [], []),
    'listJobs' : IDL.Func([IDL.Nat, IDL.Nat], [PageResult], ['query']),
    'markJobComplete' : IDL.Func(
        [JobId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'registerUser' : IDL.Func([RegisterRequest], [UserProfile], []),
    'searchJobs' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [PageResult],
        ['query'],
      ),
    'topUpBalance' : IDL.Func(
        [IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateCallerUserProfile' : IDL.Func(
        [UpdateProfileRequest],
        [UserProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };