/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export type JobId = bigint;
export interface JobView {
    id: JobId;
    title: string;
    postedBy?: UserId;
    contactInfo: string;
    postedDate: Timestamp;
    jobStatus: JobStatus;
    assignedWorker?: UserId;
    isRemote: boolean;
    description: string;
    category: Category;
    salaryMax: bigint;
    salaryMin: bigint;
    requirements: string;
    location: string;
}
export type UserId = Principal;
export interface UpdateProfileRequest {
    city: BoliviaCity;
    name: string;
    phone: string;
}
export interface AddJobRequest {
    title: string;
    contactInfo: string;
    isRemote: boolean;
    description: string;
    category: Category;
    salaryMax: bigint;
    salaryMin: bigint;
    requirements: string;
    location: string;
}
export interface RegisterRequest {
    city: BoliviaCity;
    name: string;
    role: UserRole;
    email: string;
    phone: string;
}
export interface PageResult {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<JobView>;
}
export interface UserProfile {
    id: UserId;
    balance: number;
    city: BoliviaCity;
    name: string;
    role: UserRole;
    email: string;
    profileStatus: ProfileStatus;
    phone: string;
    registeredAt: Timestamp;
}
export enum BoliviaCity {
    LaPaz = "LaPaz",
    Sucre = "Sucre",
    Beni = "Beni",
    Potosi = "Potosi",
    Cochabamba = "Cochabamba",
    Pando = "Pando",
    SantaCruz = "SantaCruz",
    Tarija = "Tarija",
    Oruro = "Oruro",
    ElAlto = "ElAlto"
}
export enum Category {
    Electricista = "Electricista",
    Mecanico = "Mecanico",
    Plomero = "Plomero",
    Albanil = "Albanil",
    Carpintero = "Carpintero",
    Soldador = "Soldador",
    Pintor = "Pintor",
    Otros = "Otros",
    Jardinero = "Jardinero"
}
export enum JobStatus {
    Posted = "Posted",
    Cancelled = "Cancelled",
    PendingApproval = "PendingApproval",
    InProgress = "InProgress",
    Completed = "Completed"
}
export enum ProfileStatus {
    Active = "Active",
    Suspended = "Suspended"
}
export enum UserRole {
    Trabajador = "Trabajador",
    Cliente = "Cliente"
}
export interface backendInterface {
    addJob(req: AddJobRequest): Promise<JobView>;
    applyForJob(jobId: JobId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    approveJob(jobId: JobId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    filterJobsByCategory(category: Category, offset: bigint, limit: bigint): Promise<PageResult>;
    filterJobsByLocation(location: string, offset: bigint, limit: bigint): Promise<PageResult>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getJob(id: JobId): Promise<JobView | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkerBalance(): Promise<number>;
    initSampleData(): Promise<void>;
    listJobs(offset: bigint, limit: bigint): Promise<PageResult>;
    markJobComplete(jobId: JobId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerUser(req: RegisterRequest): Promise<UserProfile>;
    searchJobs(keyword: string, offset: bigint, limit: bigint): Promise<PageResult>;
    topUpBalance(amount: number): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateCallerUserProfile(req: UpdateProfileRequest): Promise<UserProfile>;
}
import type { AddJobRequest as _AddJobRequest, BoliviaCity as _BoliviaCity, Category as _Category, JobId as _JobId, JobStatus as _JobStatus, JobView as _JobView, PageResult as _PageResult, ProfileStatus as _ProfileStatus, RegisterRequest as _RegisterRequest, Timestamp as _Timestamp, UpdateProfileRequest as _UpdateProfileRequest, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addJob(arg0: AddJobRequest): Promise<JobView> {
        if (this.processError) {
            try {
                const result = await this.actor.addJob(to_candid_AddJobRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_JobView_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addJob(to_candid_AddJobRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_JobView_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async applyForJob(arg0: JobId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForJob(arg0);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForJob(arg0);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveJob(arg0: JobId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.approveJob(arg0);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveJob(arg0);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterJobsByCategory(arg0: Category, arg1: bigint, arg2: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.filterJobsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_PageResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterJobsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_PageResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterJobsByLocation(arg0: string, arg1: bigint, arg2: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.filterJobsByLocation(arg0, arg1, arg2);
                return from_candid_PageResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterJobsByLocation(arg0, arg1, arg2);
            return from_candid_PageResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: JobId): Promise<JobView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerBalance(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerBalance();
            return result;
        }
    }
    async initSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSampleData();
            return result;
        }
    }
    async listJobs(arg0: bigint, arg1: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobs(arg0, arg1);
                return from_candid_PageResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobs(arg0, arg1);
            return from_candid_PageResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async markJobComplete(arg0: JobId): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.markJobComplete(arg0);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markJobComplete(arg0);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: RegisterRequest): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(to_candid_RegisterRequest_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(to_candid_RegisterRequest_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchJobs(arg0: string, arg1: bigint, arg2: bigint): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJobs(arg0, arg1, arg2);
                return from_candid_PageResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJobs(arg0, arg1, arg2);
            return from_candid_PageResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async topUpBalance(arg0: number): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.topUpBalance(arg0);
                return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.topUpBalance(arg0);
            return from_candid_variant_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCallerUserProfile(arg0: UpdateProfileRequest): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCallerUserProfile(to_candid_UpdateProfileRequest_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCallerUserProfile(to_candid_UpdateProfileRequest_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BoliviaCity_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BoliviaCity): BoliviaCity {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_JobView_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobView): JobView {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_PageResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageResult): PageResult {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ProfileStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfileStatus): ProfileStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobView]): JobView | null {
    return value.length === 0 ? null : from_candid_JobView_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<_JobView>;
}): {
    total: bigint;
    offset: bigint;
    limit: bigint;
    items: Array<JobView>;
} {
    return {
        total: value.total,
        offset: value.offset,
        limit: value.limit,
        items: from_candid_vec_n15(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    balance: number;
    city: _BoliviaCity;
    name: string;
    role: _UserRole;
    email: string;
    profileStatus: _ProfileStatus;
    phone: string;
    registeredAt: _Timestamp;
}): {
    id: UserId;
    balance: number;
    city: BoliviaCity;
    name: string;
    role: UserRole;
    email: string;
    profileStatus: ProfileStatus;
    phone: string;
    registeredAt: Timestamp;
} {
    return {
        id: value.id,
        balance: value.balance,
        city: from_candid_BoliviaCity_n19(_uploadFile, _downloadFile, value.city),
        name: value.name,
        role: from_candid_UserRole_n21(_uploadFile, _downloadFile, value.role),
        email: value.email,
        profileStatus: from_candid_ProfileStatus_n23(_uploadFile, _downloadFile, value.profileStatus),
        phone: value.phone,
        registeredAt: value.registeredAt
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    title: string;
    postedBy: [] | [_UserId];
    contactInfo: string;
    postedDate: _Timestamp;
    jobStatus: _JobStatus;
    assignedWorker: [] | [_UserId];
    isRemote: boolean;
    description: string;
    category: _Category;
    salaryMax: bigint;
    salaryMin: bigint;
    requirements: string;
    location: string;
}): {
    id: JobId;
    title: string;
    postedBy?: UserId;
    contactInfo: string;
    postedDate: Timestamp;
    jobStatus: JobStatus;
    assignedWorker?: UserId;
    isRemote: boolean;
    description: string;
    category: Category;
    salaryMax: bigint;
    salaryMin: bigint;
    requirements: string;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        postedBy: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.postedBy)),
        contactInfo: value.contactInfo,
        postedDate: value.postedDate,
        jobStatus: from_candid_JobStatus_n8(_uploadFile, _downloadFile, value.jobStatus),
        assignedWorker: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.assignedWorker)),
        isRemote: value.isRemote,
        description: value.description,
        category: from_candid_Category_n10(_uploadFile, _downloadFile, value.category),
        salaryMax: value.salaryMax,
        salaryMin: value.salaryMin,
        requirements: value.requirements,
        location: value.location
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Electricista: null;
} | {
    Mecanico: null;
} | {
    Plomero: null;
} | {
    Albanil: null;
} | {
    Carpintero: null;
} | {
    Soldador: null;
} | {
    Pintor: null;
} | {
    Otros: null;
} | {
    Jardinero: null;
}): Category {
    return "Electricista" in value ? Category.Electricista : "Mecanico" in value ? Category.Mecanico : "Plomero" in value ? Category.Plomero : "Albanil" in value ? Category.Albanil : "Carpintero" in value ? Category.Carpintero : "Soldador" in value ? Category.Soldador : "Pintor" in value ? Category.Pintor : "Otros" in value ? Category.Otros : "Jardinero" in value ? Category.Jardinero : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    LaPaz: null;
} | {
    Sucre: null;
} | {
    Beni: null;
} | {
    Potosi: null;
} | {
    Cochabamba: null;
} | {
    Pando: null;
} | {
    SantaCruz: null;
} | {
    Tarija: null;
} | {
    Oruro: null;
} | {
    ElAlto: null;
}): BoliviaCity {
    return "LaPaz" in value ? BoliviaCity.LaPaz : "Sucre" in value ? BoliviaCity.Sucre : "Beni" in value ? BoliviaCity.Beni : "Potosi" in value ? BoliviaCity.Potosi : "Cochabamba" in value ? BoliviaCity.Cochabamba : "Pando" in value ? BoliviaCity.Pando : "SantaCruz" in value ? BoliviaCity.SantaCruz : "Tarija" in value ? BoliviaCity.Tarija : "Oruro" in value ? BoliviaCity.Oruro : "ElAlto" in value ? BoliviaCity.ElAlto : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Trabajador: null;
} | {
    Cliente: null;
}): UserRole {
    return "Trabajador" in value ? UserRole.Trabajador : "Cliente" in value ? UserRole.Cliente : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Suspended: null;
}): ProfileStatus {
    return "Active" in value ? ProfileStatus.Active : "Suspended" in value ? ProfileStatus.Suspended : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Posted: null;
} | {
    Cancelled: null;
} | {
    PendingApproval: null;
} | {
    InProgress: null;
} | {
    Completed: null;
}): JobStatus {
    return "Posted" in value ? JobStatus.Posted : "Cancelled" in value ? JobStatus.Cancelled : "PendingApproval" in value ? JobStatus.PendingApproval : "InProgress" in value ? JobStatus.InProgress : "Completed" in value ? JobStatus.Completed : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobView>): Array<JobView> {
    return value.map((x)=>from_candid_JobView_n5(_uploadFile, _downloadFile, x));
}
function to_candid_AddJobRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddJobRequest): _AddJobRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_BoliviaCity_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BoliviaCity): _BoliviaCity {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterRequest_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterRequest): _RegisterRequest {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProfileRequest_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProfileRequest): _UpdateProfileRequest {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    contactInfo: string;
    isRemote: boolean;
    description: string;
    category: Category;
    salaryMax: bigint;
    salaryMin: bigint;
    requirements: string;
    location: string;
}): {
    title: string;
    contactInfo: string;
    isRemote: boolean;
    description: string;
    category: _Category;
    salaryMax: bigint;
    salaryMin: bigint;
    requirements: string;
    location: string;
} {
    return {
        title: value.title,
        contactInfo: value.contactInfo,
        isRemote: value.isRemote,
        description: value.description,
        category: to_candid_Category_n3(_uploadFile, _downloadFile, value.category),
        salaryMax: value.salaryMax,
        salaryMin: value.salaryMin,
        requirements: value.requirements,
        location: value.location
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: BoliviaCity;
    name: string;
    role: UserRole;
    email: string;
    phone: string;
}): {
    city: _BoliviaCity;
    name: string;
    role: _UserRole;
    email: string;
    phone: string;
} {
    return {
        city: to_candid_BoliviaCity_n28(_uploadFile, _downloadFile, value.city),
        name: value.name,
        role: to_candid_UserRole_n30(_uploadFile, _downloadFile, value.role),
        email: value.email,
        phone: value.phone
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: BoliviaCity;
    name: string;
    phone: string;
}): {
    city: _BoliviaCity;
    name: string;
    phone: string;
} {
    return {
        city: to_candid_BoliviaCity_n28(_uploadFile, _downloadFile, value.city),
        name: value.name,
        phone: value.phone
    };
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BoliviaCity): {
    LaPaz: null;
} | {
    Sucre: null;
} | {
    Beni: null;
} | {
    Potosi: null;
} | {
    Cochabamba: null;
} | {
    Pando: null;
} | {
    SantaCruz: null;
} | {
    Tarija: null;
} | {
    Oruro: null;
} | {
    ElAlto: null;
} {
    return value == BoliviaCity.LaPaz ? {
        LaPaz: null
    } : value == BoliviaCity.Sucre ? {
        Sucre: null
    } : value == BoliviaCity.Beni ? {
        Beni: null
    } : value == BoliviaCity.Potosi ? {
        Potosi: null
    } : value == BoliviaCity.Cochabamba ? {
        Cochabamba: null
    } : value == BoliviaCity.Pando ? {
        Pando: null
    } : value == BoliviaCity.SantaCruz ? {
        SantaCruz: null
    } : value == BoliviaCity.Tarija ? {
        Tarija: null
    } : value == BoliviaCity.Oruro ? {
        Oruro: null
    } : value == BoliviaCity.ElAlto ? {
        ElAlto: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    Trabajador: null;
} | {
    Cliente: null;
} {
    return value == UserRole.Trabajador ? {
        Trabajador: null
    } : value == UserRole.Cliente ? {
        Cliente: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    Electricista: null;
} | {
    Mecanico: null;
} | {
    Plomero: null;
} | {
    Albanil: null;
} | {
    Carpintero: null;
} | {
    Soldador: null;
} | {
    Pintor: null;
} | {
    Otros: null;
} | {
    Jardinero: null;
} {
    return value == Category.Electricista ? {
        Electricista: null
    } : value == Category.Mecanico ? {
        Mecanico: null
    } : value == Category.Plomero ? {
        Plomero: null
    } : value == Category.Albanil ? {
        Albanil: null
    } : value == Category.Carpintero ? {
        Carpintero: null
    } : value == Category.Soldador ? {
        Soldador: null
    } : value == Category.Pintor ? {
        Pintor: null
    } : value == Category.Otros ? {
        Otros: null
    } : value == Category.Jardinero ? {
        Jardinero: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
